

/** IMPORTANT: MUST HAVE SAME VALUE AS IN CONFIG.PGP */
window.ERROR_PARSER_START = "START-MARKER-TYPED-OUT-FOR-ERROR-PARSER";
window.ERROR_PARSER_END   = "END-MARKER-TYPED-OUT-FOR-ERROR-PARSER";




